stages:
- name: Publish image
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: minecraft-server:${CICD_EXECUTION_SEQUENCE}
  when:
    branch:
      include:
      - master
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./deploy/deployment.yml
  when:
    branch:
      include:
      - master
