apiVersion: apps/v1beta2
kind: Deployment
metadata:
  generation: 1
  name: minecraft-server
  namespace: minecraft
spec:
  replicas: 1
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-minecraft-minecraft-server
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        workload.user.cattle.io/workloadselector: deployment-minecraft-minecraft-server
    spec:
      imagePullSecrets:
      - name: pipeline-docker-registry
      restartPolicy: Always
      containers:
      - image: ${CICD_IMAGE}:${CICD_EXECUTION_SEQUENCE}
        name: minecraft-server
        volumeMounts:
        - mountPath: /usr/app/server
          name: minecraft-server
      volumes:
      - name: minecraft-server
        persistentVolumeClaim:
          claimName: minecraft-server
